export const artistData = [
    {
        id: 1,
        name: 'Xeon Diversity',
        role: 'Composer',
        about: 'Future Bass',
        imgSrc: '/artist/xeondiversity.png',
    },
    {
        id: 2,
        name: 'GoGoN-',
        role: 'Composer',
        about: 'suka dangdut tapi gak pernah bikin dangdut :"',
        imgSrc: '/artist/gogon.png',
    },
    {
        id: 3,
        name: 'Dispel',
        role: 'Composer',
        about: 'Fuses live instruments such as orchestras and folk as one song.',
        imgSrc: '/artist/dispel.png',
    },
    {
        id: 4,
        name: 'RESiTY',
        role: 'Composer',
        about: 'Future Bass',
        imgSrc: '/img/luminoz.png',
    },
    {
        id: 5,
        name: 'Rakakun-',
        role: 'Composer',
        about: 'Future Bass',
        imgSrc: '/img/luminoz.png',
    },
    {
        id: 6,
        name: 'SM-MEGAtive',
        role: 'Composer',
        about: 'Future Bass',
        imgSrc: '/img/luminoz.png',
    },
    {
        id: 7,
        name: 'Altair Aquila',
        role: 'Composer',
        about: 'VTuber',
        imgSrc: '/img/luminoz.png',
    },
    {
        id: 8,
        name: 'sarochi',
        role: 'Composer',
        about: 'Future Bass',
        imgSrc: '/img/luminoz.png',
    },
    {
        id: 9,
        name: 'Scarlet',
        role: 'Composer',
        about: 'Future Bass',
        imgSrc: '/img/luminoz.png',
    },
    {
        id: 10,
        name: 'Mariela Riona',
        role: 'Vocalist',
        about: 'VTuber',
        imgSrc: '/img/luminoz.png',
    },
    {
        id: 11,
        name: 'Evara Lyrissha',
        role: 'Vocalist',
        about: 'VTuber',
        imgSrc: '/img/luminoz.png',
    },
    {
        id: 12,
        name: 'Saryulis',
        role: 'Composer',
        about: 'Future Bass',
        imgSrc: '/img/luminoz.png',
    },
    {
        id: 13,
        name: 'KURORYU',
        role: 'Composer',
        about: 'a weeb who like making music, just a simple guy make a simple track, focused on genre like Hardcore/Dubstep/Drum n Bass/etc.',
        imgSrc: '/artist/kuroryu.png',
    },
];